# Generated by Django 6.1.1 on 2026-09-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL-TIME', 'full-time'), ('PART-TIME', 'part-time')], default='part-time', max_length=100),
        ),
    ]
