# Generated by Django 6.1.1 on 2026-09-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL-TIME', 'full-time'), ('PART-TIME', 'part-time')], max_length=100),
        ),
    ]
